### ISSUE TITLE
No SSL for WebSocket connections

### ISSUE THREAD

**Issue by auchenberg** [auchenberg/devtools-remote#3]
Chrome DevTools doesn't seem to support SSL WebSocket connections.

**Comment by auchenberg** [comment]
@paulirish Do you know if the DevTools front-end supports WSS?

**Comment by kzahel** [comment]
I don't see why it wouldn't work: https://github.com/ChromeDevTools/devtools-frontend/blob/master/front_end/sdk/Connections.js#L117
just passing in wss:// instead of ws:// right?

**Comment by paulirish** [comment]
I believe the problem may be here: https://github.com/ChromeDevTools/devtools-frontend/blob/32506bf47f1a3d38e5b435ff68ef07abfaac52d7/front_end/sdk/TargetManager.js#L424-L426

```js
  _createMainConnection(params) {
    if (Runtime.queryParam('ws')) {
      var ws = 'ws://' + Runtime.queryParam('ws');
```

If you guys want, we can add support for a `wss` query parameter. Assuming this has value to yall..

**Comment by auchenberg** [comment]
Yup @paulirish the problem is how querystring is used. That would be wonderful! Would close the big security gap when remoting over the wire.

**Comment by paulirish** [comment]
Nice. does this look about right to you? https://codereview.chromium.org/2729623006

**Comment by auchenberg** [comment]
@paulirish Yup looks legit 👍

**Comment by paulirish** [comment]
resolved on the devtools side

**Comment by auchenberg** [comment]
Now back online at https://remote.devtools.rocks/
